name: Build docs with Simulate for Web
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --release --base-href /simulate/web/
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip  
          python3 -m pip install mkdocs      
          python3 -m pip install mkdocs-material
          python3 -m pip install pymdown-extensions
          python3 -m pip install mkdocs-git-revision-date-localized-plugin
      - name: Git setup and update
        run: |
          git config user.name "GitHub Action" && git config user.email "github-action@github.com"
          git fetch origin
      - name: Build Docs
        run: mkdocs build
      - name: Add latest web build and deploy
        run: |
          mv build/web/ site/
          mkdocs gh-deploy --dirty
